d-fine/Dataland

documentation/architecture.drawio

This PR adds an arrow to the CRIF-data-provider-Box from the User, and removes a needless textbox
*Only Documentation, no new feature*
*Only Documentation, no new feature*
*Only Documentation, no new feature*
*Only Documentation, no new feature*
*Only Documentation, no new feature*
*Only Documentation, no new feature*

Dala 47 bugfix architecture diagram

---

.github/workflows/CI.yaml
baseDockerfiles/cypressBaseImageDockerfile
build.gradle.kts
buildDockerImage.sh
dataland-frontend/Dockerfile

`Speed up of e2e tests by npm caching`
*Ist nur ein Teilfeature - CI verbesserung. DoD irrelevant*
*Ist nur ein Teilfeature - CI verbesserung. Jira Ticket irrelevant*
*Wird in jedem Build benutzt*
*nicht nötig*

Dala 65 ci optimization

---

documentation/architecture.drawio

add DatalandEDC and PostgreSQL to architecture diagram

---

.github/workflows/CD.yaml
README.md
dataland-backend/build.gradle.kts
dataland-backend/src/main/resources/application.properties
dataland-frontend/cypress.json
dataland-frontend/package-lock.json
dataland-frontend/package.json
dataland-frontend/tests/e2e/plugins/index.js
dataland-frontend/tests/e2e/specs/verify_deployment/verify_deployment.ts
docker-compose.yml
testing/execute_e2e_tests.sh
testing/wait_for_backend_and_run_e2etests.sh

This Pull Request adds a "Smoke Test" to Preview: All our E2E Cypress Tests will also be executed against preview after an deployment. This causes a) dummy data to be in preview and b) it verifies that the deployment actually worked and nothing broke.
_New feature is a test itself_

Dala 80 check that preview is running

---

.github/workflows/CD.yaml

CD should be run automatically when there is a push in main

CD: Run CD by push into main

---

dataland-frontend/src/components/resources/landing/MarketingSection.vue

Dala 224 video

---

dataland-frontend/src/components/resources/landing/MarketingSection.vue

change youtube video URL

---

.github/workflows/CD.yaml
dataland-frontend/src/components/resources/landing/MarketingSection.vue
dataland-frontend/tests/e2e/specs/low/pages/taxonomy/SearchTaxonomy.ts
deployment/start_and_deploy_to_server.sh
environments/.env.template

This PR fixes the broken env-template, such that the trustee gets its own keycloak back.

fixes broken env template

---

dataland-frontend/src/components/resources/taxonomy/search/EuTaxoSearchResults.vue
dataland-frontend/tests/e2e/specs/low/pages/taxonomy/SearchTaxonomy.ts

DALA 344 Fixed Euro-Sign alignment in DataTable

---

dataland-frontend/.eslintignore
dataland-frontend/build.gradle.kts
dataland-frontend/src/services/ApiClients.ts
dataland-frontend/src/utils/SearchTaxonomyPageCompanyDataRequester.ts
dataland-frontend/tests/e2e/specs/company-metadata/TaxonomySearch.ts
dataland-frontend/tests/e2e/specs/prepopulation/AwaitPrepopulation.ts
dataland-frontend/tests/e2e/specs/prepopulation/Prepopulation.ts

DALA-451 Add Typescript Type-Safety to Frontend API Calls

---

README.md

Update mainenance description

---

dataland-frontend/src/components/pages/SearchCompaniesForFrameworkData.vue
dataland-frontend/src/components/resources/frameworkDataSearch/IndexTabMenu.vue
dataland-frontend/tests/e2e/specs/company-metadata/SearchIndexTabMenu.ts

Use auto-generated models

---

settings.gradle.kts
testing/execute_e2e_tests.sh

DALA-520 Revert logging update

---

.github/workflows/CD.yaml
.github/workflows/CI.yaml

Dala 831 logging issue

---

.github/workflows/RebuildDockerImages.yaml
base-dockerfiles/GradleDockerfile
build-utils/base_rebuild_gradle_dockerfile.sh
build-utils/base_rebuild_single_docker_image.sh
dataland-backend/DatalandBackendBaseDockerfile
dataland-e2etests/Dockerfile
dataland-e2etests/e2etestsCoreDockerfile
dataland-e2etests/src/test/kotlin/org/dataland/e2etests/tests/MalformedRawRequestTests.kt
dataland-frontend/Dockerfile
dataland-frontend/DockerfileTest
dataland-keycloak/Dockerfile
startDevelopmentStack.sh

Dala 464 avoid local push and use caches

---

build.gradle.kts

fixes coverage calculations

---

dataland-frontend/src/router/index.ts

dynamically load components in router

---

README.md
build.gradle.kts
dataland-frontend/src/assets/scss/components/cards.scss
dataland-frontend/src/components/pages/ApiKeysPage.vue
dataland-frontend/src/components/resources/frameworkDataSearch/euTaxonomy/EuTaxoCard.vue
dataland-frontend/src/components/resources/frameworkDataSearch/euTaxonomy/EuTaxonomyPanelFinancials.vue
dataland-frontend/src/components/resources/frameworkDataSearch/euTaxonomy/EuTaxonomyPanelNonFinancials.vue
dataland-frontend/src/components/resources/landing/LandingLogin.vue
dataland-frontend/src/utils/DateFormatUtils.ts
dataland-frontend/tests/e2e/specs/user-api-key/GenerateApiKey.ts

Dala 1027 fix frontend issues

---

.github/PULL_REQUEST_TEMPLATE/manual_maintenance.md

add tasks for manual maintenance

---

.github/workflows/CD.yaml

New real data

---

dataland-keycloak/start_keycloak.sh

fix broken env substitution in start_keycloak.sh and add validators to avoid this in future

---

deployment/initialize_keycloak.sh

fix for counting

---

deployment/initialize_keycloak.sh

don't rely on that technical users are within first 100

---

dataland-backend/src/main/kotlin/org/dataland/datalandbackend/controller/DataController.kt
dataland-backend/src/main/kotlin/org/dataland/datalandbackend/controller/InviteController.kt
dataland-backend/src/main/kotlin/org/dataland/datalandbackend/services/DataManager.kt
dataland-backend/src/test/kotlin/org/dataland/datalandbackend/services/DataManagerTest.kt
dataland-internal-storage/src/main/kotlin/org/dataland/datalandinternalstorage/services/DatabaseDataStore.kt
dataland-message-queue-utils/src/main/kotlin/org/dataland/datalandmessagequeueutils/exceptions/MessageQueueRejectException.kt
dataland-message-queue-utils/src/main/kotlin/org/dataland/datalandmessagequeueutils/utils/MessageQueueUtils.kt

Fix the Transaction Handling in relation with Messages

Dala 1318 fix e2e tests

---

.github/PULL_REQUEST_TEMPLATE/manual_maintenance.md
dataland-rabbitmq/rabbitmq.conf
docker-compose.yml

Dala 1344 adjust rabbit mq disk and ram usage

---

dataland-backend/src/main/kotlin/org/dataland/datalandbackend/repositories/StoredCompanyRepository.kt

Dala 1342 unrecognized query hint

---

dataland-frontend/src/components/forms/CreateEUTaxonomyForFinancials.vue
dataland-frontend/src/components/forms/CreateEUTaxonomyForNonFinancials.vue
dataland-frontend/src/components/forms/parts/kpiSelection/DataPointForm.vue
dataland-frontend/tests/e2e/utils/EuTaxonomyFinancialsUpload.ts
dataland-frontend/tests/e2e/utils/EuTaxonomyNonFinancialsUpload.ts

Dala 1588 fix negative page numbers

---

dataland-frontend/src/components/forms/parts/elements/derived/NaceCodeTree.ts
dataland-frontend/tests/e2e/utils/LksgUpload.ts

The tree model of NACE codes based on a old version (v1.1). 
This PR contains the update to NACE codes v2.0

DALA 1626 update the NACE Codes

---

dataland-frontend/src/components/forms/parts/elements/derived/AddressFormElement.vue

remove required attribute from strand and postal code in frontend

---

dataland-frontend/src/components/resources/frameworkDataSearch/lksg/LksgDataModel.ts
docker-compose.yml

update data model file including ordering

---

testing/e2e_test_launcher.sh

try with docker-compose 2.20.0

---

dataland-frontend/src/components/resources/frameworkDataSearch/lksg/LksgDataModel.ts
dataland-frontend/src/components/resources/frameworkDataSearch/lksg/LksgPanel.vue
dataland-frontend/src/components/resources/frameworkDataSearch/sme/SmePanel.vue
dataland-frontend/src/utils/NaceCodeConverter.ts

Dala 2131 sme viewpage small fixes

---

.github/workflows/CD.yaml
.github/workflows/CI.yaml
dataland-frontend/tests/component/components/pages/ApiKeyPage.cy.ts
testing/execute_frontend_component_tests.sh

Fix incorrect frontend component test ci results

---

.github/PULL_REQUEST_TEMPLATE/manual_maintenance.md
dataland-frontend/src/components/generics/ViewMultipleDatasetsDisplayBase.vue
dataland-frontend/src/components/generics/ViewSingleDatasetDisplayBase.vue
dataland-frontend/src/utils/SessionTimeoutUtils.ts

Dala 2251 sonar code smells mm49

---

dataland-internal-storage/src/main/kotlin/db/migration/V5__MigrateToNewEuTaxonomyForNonFinancials.kt
dataland-internal-storage/src/test/kotlin/db/migration/V5__MigrateToNewEuTaxonomyForNonFinancialsTest.kt
dataland-internal-storage/src/test/resources/db/migration/V5/oldExpectedTransformedDatabaseEntry.json
dataland-internal-storage/src/test/resources/db/migration/V5/oldExpectedTransformedDatabaseEntry2.json
dataland-internal-storage/src/test/resources/db/migration/V5/oldOriginalDatabaseEntry.json
dataland-internal-storage/src/test/resources/db/migration/V5/oldOriginalDatabaseEntry2.json

DALA 2334 fix migration issue

---

dataland-frontend/tests/e2e/specs/landing-page/FooterSection.ts
dataland-frontend/tests/e2e/specs/search-company-framework-data/SearchCompaniesForFrameworkData.ts

Dala 2330 disable footer section tests

---

dataland-frontend/src/utils/Formatter.ts
dataland-frontend/tests/component/components/resources/frameworkDataSearch/euTaxoNonFinancials/EuTaxonomyForNonFinancialsPanel.cy.ts
testing/data/EuTaxonomyForNonFinancialsMocks.json

`Nimanshi discovered that a total revenue of 0 does not appear as 0 on the view page.`
are merged

fix missing-nullish-number-bug discovered by Nimanshi

---

dataland-backend/backendOpenApi.json
dataland-backend/src/main/kotlin/org/dataland/datalandbackend/utils/JsonExampleFormattingConstants.kt
dataland-frontend/tests/e2e/specs/swagger-ui/Swagger.ts

Fix swagger examples

---

dataland-frontend/src/assets/content.json
dataland-frontend/src/components/generics/TheNewFooter.vue
dataland-frontend/src/components/pages/NewLandingPage.vue

content update + footer fix

---

.github/pull_request_template.md
migrateData.sh

change PR as discussed in retro

---

dataland-frontend/src/assets/content.json
dataland-frontend/src/components/resources/newLandingPage/TheQuotes.vue
dataland-frontend/tests/component/components/pages/LandingPage.cy.ts

Dala 2755 new video

---

dataland-frontend/src/assets/content.json
dataland-frontend/src/components/resources/newLandingPage/TheQuotes.vue

Change one video on landing page and add another

---

dataland-frontend/src/assets/content.json
dataland-frontend/src/components/resources/newLandingPage/TheQuotes.vue
dataland-frontend/tests/component/components/pages/LandingPage.cy.ts

adds new video and quote

---

dataland-frontend/src/components/generics/TheNewHeader.vue
dataland-frontend/src/components/resources/newLandingPage/TheQuotes.vue
dataland-frontend/tests/e2e/specs/eu-taxonomy-non-financials/DataIntegrity.ts

DALA-2936 - fix odd slides bug

---

dataland-frontend/src/assets/content.json

DALA-3006 - video update

---

dataland-frontend/src/assets/content.json
dataland-frontend/tests/component/components/pages/LandingPage.cy.ts

DALA-3164 - video testimonial

---

dataland-frontend/src/assets/content.json
dataland-frontend/tests/component/components/pages/LandingPage.cy.ts

DALA-3165 - video testimonial d-fine

---

dataland-frontend/src/assets/content.json

Dala 3210 video update

---

dataland-frontend/src/assets/content.json

WWF new testimonial

---

dataland-frontend/src/assets/content.json

`<New testimonial video (BVI)>`
are merged

adds new testimonial video (BVI)

---

dataland-frontend/src/components/pages/DataPrivacy.vue

changes to privacy statement for events

---

dataland-community-manager/communityManagerOpenApi.json
dataland-community-manager/src/main/kotlin/org/dataland/datalandcommunitymanager/model/dataRequest/SingleDataRequest.kt
dataland-community-manager/src/test/kotlin/org/dataland/datalandcommunitymanager/email/BulkDataRequestEmailMessageSenderTest.kt
dataland-community-manager/src/test/kotlin/org/dataland/datalandcommunitymanager/email/DataRequestedAnsweredEmailMessageSenderTest.kt
dataland-community-manager/src/test/kotlin/org/dataland/datalandcommunitymanager/email/SingleDataRequestEmailMessageSenderTest.kt
dataland-community-manager/src/test/kotlin/org/dataland/datalandcommunitymanager/services/DataRequestAlterationManagerTest.kt
dataland-e2etests/src/test/kotlin/org/dataland/e2etests/tests/communityManager/DataRequestUploadListenerTest.kt
dataland-e2etests/src/test/kotlin/org/dataland/e2etests/tests/communityManager/SingleDataRequestsTest.kt
dataland-frontend/tests/e2e/specs/user-authentication/Register.ts
dataland-keycloak/start_keycloak.sh
deployment/initialize_keycloak.sh

Change additional test domains to example.com
are merged

DALA-3750 Change additional test domains to example.com

---

.github/workflows/CD.yaml
.github/workflows/CI.yaml
README.md
build.gradle.kts
dataland-api-key-manager/build.gradle.kts
dataland-backend-utils/build.gradle.kts
dataland-backend/build.gradle.kts
dataland-batch-manager/build.gradle.kts
dataland-community-manager/build.gradle.kts
dataland-document-manager/build.gradle.kts
dataland-e2etests/build.gradle.kts
dataland-email-service/build.gradle.kts
dataland-framework-toolbox/build.gradle.kts
dataland-frontend/build.gradle.kts
dataland-frontend/tests/e2e/specs/community/SingleDataRequest.ts
dataland-frontend/tests/e2e/specs/prepopulation/Prepopulation.ts
dataland-internal-storage/build.gradle.kts
dataland-keycloak-adapter/build.gradle.kts
dataland-qa-service/build.gradle.kts

Dala 3754 fix flaky test and remove some sending of email

---

dataland-frontend/src/components/pages/DataPrivacy.vue
dataland-frontend/src/components/pages/SingleDataRequest.vue

updating data privacy

---

dataland-frontend/tests/e2e/specs/heimathafen/DataIntegrity.ts
dataland-frontend/tests/e2e/specs/user-api-key/GenerateApiKey.ts

Dala 3981 stabilize flaky e2e tests

---

dataland-automated-qa-service/requirements.txt

Update dependency pytest to v8.1.2

---

dataland-frontend/src/assets/content.json

Removed video from Jonas Weisbach and added video from Stephan Henkel to content.json

DALA-4349_Add-video-and-remove-video

---

dataland-frontend/src/components/generics/ViewFrameworkBase.vue

Fix bug that data download not available for P2P

---

dataland-pgadmin/Dockerfile

Note: To create a PR using this template add the query parameter `template=manual_maintenance.md` to the merge request
creation URL (or simply copy this md file into the description)
- See 'Problematic Updates' in the wiki (evaluate if issues persist or if newer versions are available that fix them)
consult the internal Dataland Wiki.
then update the version number used in docker-compose.
the currently used version of the client.
1. Edit the docker compose file by adding a `ports` section with the entry `"8080:8080"` to the "eurodat-client" and start it
2. Open a shell and navigate to the `dataland-eurodat-client` subproject
3. Execute the following snippet of code (requires python): `curl http://localhost:8080/api/v1/client-controller/openapi | sed 's/\(example: \)\([^ ]*\)/\1"\2"/g' | …

Manual Maintenance 81 - part 1

---

dataland-e2etests/DockerfileBase
dataland-frontend/package-lock.json
dataland-frontend/package.json
dataland-keycloak/dataland_theme/login/package-lock.json
dataland-keycloak/dataland_theme/login/package.json
package-lock.json
package.json

DALA-5919-1: First batch of minor updates

---

dataland-frontend/package-lock.json
dataland-frontend/package.json
dataland-keycloak/dataland_theme/login/package-lock.json
dataland-keycloak/dataland_theme/login/package.json

DALA-5919-2: MM Update Batch 2

---

dataland-backend/backendOpenApi.json
dataland-e2etests/DockerfileBase
dataland-frontend/package-lock.json
dataland-keycloak/dataland_theme/login/package-lock.json
dataland-keycloak/dataland_theme/login/package.json
dataland-pgadmin/Dockerfile
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties

DALA 6017: Manual Maintenance Part3

---

dataland-frontend/package-lock.json
dataland-pgadmin/Dockerfile
gradle/libs.versions.toml

DALA 6017: Manual Maintenance Part 5
