d-fine/Dataland

.github/pull_request_template.md, dataland-frontend/tests/e2e/specs/low/pages/DataSearch.ts
This PR adapts the PR Template to the changed DoD. The DoD change is implemented under https://github.com/d-fine/DatalandInternal/wiki/DoD and was agreed on in the retrospective.
=> Dala 97 adapt dod and pr template

.github/workflows/CD.yaml, .github/workflows/CI.yaml, .github/workflows/CypressImage.yaml, .github/workflows/TemurinImage.yaml
=> Get rid of all warnings from github

.github/workflows/CD.yaml, dataland-frontend/tests/e2e/specs/prepopulation/AwaitPrepopulation.ts, dataland-frontend/tests/e2e/specs/prepopulation/Prepopulation.ts
`disable upload of data for frameworks that do not have real data`
=> Dala 1035 prevent dummy uploads when real data is used

deployment/initialize_keycloak.sh
=> Dala 2757 fix technical user handling

dataland-frontend/tests/component/components/pages/LandingPage.cy.ts, dataland-frontend/tests/e2e/specs/landing-page/LandingPage.ts, dataland-frontend/tests/e2e/specs/user-authentication/Register.ts
=> Fix flaky e2e tests

.github/workflows/CI.yaml
=> make merge step wait for all relevant tests

startDevelopmentStack.sh
=> make start script more verbose

dataland-frontend/.prettierignore, dataland-frontend/public/static/silent-check-sso.html, dataland-frontend/src/components/pages/NewLandingPage.vue
=> Dala 4379 login bug

deployment/initialize_keycloak.sh
=> DALA-4251 fix typo

dataland-frontend/.prettierignore, dataland-frontend/public/static/silent-check-sso.html, dataland-frontend/tests/e2e/specs/infrastructure/VerifyHeaders.ts, dataland-inbound-proxy/config/utils/securityHeaderMap.conf
=> cleaner fix for login bug via security headers

dataland-frontend/src/components/general/DataPointDataTable.vue, dataland-frontend/src/components/resources/frameworkDataSearch/DocumentLink.vue, dataland-frontend/tests/component/components/resources/frameworkDataSearch/DocumentLink.cy.ts
=> Dala-4583 page null bug and DALA-4220 make document links left aligned

.github/PULL_REQUEST_TEMPLATE/manual_maintenance.md
=> DALA-4752 Update Manual Maintenance template

dataland-frontend/src/components/pages/CompanyInformation.vue, dataland-frontend/src/components/resources/dataRequest/ReviewRequestButtons.vue
=> fix bug 4856 (no review buttons rendered)

dataland-frontend/src/components/pages/AdminAllRequestsOverview.vue, dataland-frontend/tests/component/components/pages/AdminAllRequestsOverview.cy.ts
Please also functional test on clone
=> Dala 4864 filter and pagination on admin requests page

.github/pull_request_template.md, renovate.json
=> Enable auto merges

dataland-email-service/src/main/kotlin/org/dataland/datalandemailservice/repositories/EmailSubscriptionRepository.kt, dataland-email-service/src/main/kotlin/org/dataland/datalandemailservice/services/EmailSubscriptionTracker.kt, dataland-email-service/src/main/kotlin/org/dataland/datalandemailservice/services/templateemail/DataRequestedClaimOwnershipEmailFactory.kt, dataland-email-service/src/main/kotlin/org/dataland/datalandemailservice/services/templateemail/SingleNotificationEmailFactory.kt, dataland-email-service/src/main/kotlin/org/dataland/datalandemailservice/services/templateemail/SummaryNotificationEmailFactory.kt, dataland-email-service/src/test/kotlin/org/dataland/datalandemailservice/services/DataRequestedClaimOwnershipEmailFactoryTest.kt, dataland-email-service/src/test/kotlin/org/dataland/datalandemailservice/services/EmailSubscriptionTrackerTest.kt, dataland-email-service/src/test/kotlin/org/dataland/datalandemailservice/services/NotificationEmailFactoriesTest.kt, deployment/start_and_deploy_to_server.sh
=> Bug fix email service

dataland-community-manager/src/main/kotlin/db/migration/V9__DropDataTypeEnumConstraint.kt, dataland-community-manager/src/main/kotlin/org/dataland/datalandcommunitymanager/converters/DataTypEnumAttributeConverter.kt, dataland-community-manager/src/main/kotlin/org/dataland/datalandcommunitymanager/entities/ElementaryEventEntity.kt, dataland-community-manager/src/main/kotlin/org/dataland/datalandcommunitymanager/services/elementaryEventProcessing/BaseEventProcessor.kt, dataland-community-manager/src/main/kotlin/org/dataland/datalandcommunitymanager/services/elementaryEventProcessing/PrivateDataUploadProcessor.kt, dataland-community-manager/src/main/kotlin/org/dataland/datalandcommunitymanager/services/elementaryEventProcessing/PublicDataUploadProcessor.kt, dataland-community-manager/src/test/kotlin/org/dataland/datalandcommunitymanager/services/PublicDataUploadProcessorTest.kt, dataland-qa-service/src/main/kotlin/org/dataland/datalandqaservice/services/QaEventListenerQaService.kt
=> Dala 5149 prod crash

dataland-community-manager/src/main/kotlin/org/dataland/datalandcommunitymanager/services/DataRequestQueryManager.kt, dataland-community-manager/src/test/kotlin/org/dataland/datalandcommunitymanager/services/DataRequestQueryManagerTest.kt, dataland-e2etests/src/test/kotlin/org/dataland/e2etests/tests/communityManager/QueryDataRequestsTest.kt
=> Dala 5264 fix get requests endpoint

.github/pull_request_template.md, .github/workflows/CD.yaml
=> GitHub workflow

dataland-backend/src/main/kotlin/org/dataland/datalandbackend/services/datapoints/AssembledDataMigrationManager.kt
=> Hotfix for migration bug

dataland-e2etests/src/test/kotlin/org/dataland/e2etests/tests/InvalidSfdrRequestTests.kt, dataland-e2etests/src/test/kotlin/org/dataland/e2etests/tests/QaReportControllerTest.kt, dataland-e2etests/src/test/kotlin/org/dataland/e2etests/tests/QaServiceTest.kt, dataland-e2etests/src/test/kotlin/org/dataland/e2etests/tests/communityManager/DataRequestUploadListenerTest.kt, dataland-e2etests/src/test/kotlin/org/dataland/e2etests/tests/communityManager/accessRequests/AccessRequestTest.kt, dataland-e2etests/src/test/kotlin/org/dataland/e2etests/tests/dataPoints/AssembledDatasetTest.kt, dataland-e2etests/src/test/kotlin/org/dataland/e2etests/tests/dataPoints/DataMigrationTest.kt, dataland-e2etests/src/test/kotlin/org/dataland/e2etests/tests/frameworks/EuTaxonomyFinancials.kt, dataland-e2etests/src/test/kotlin/org/dataland/e2etests/tests/frameworks/EuTaxonomyNonFinancials.kt, dataland-e2etests/src/test/kotlin/org/dataland/e2etests/tests/frameworks/Lksg.kt, dataland-e2etests/src/test/kotlin/org/dataland/e2etests/tests/frameworks/Sfdr.kt, dataland-e2etests/src/test/kotlin/org/dataland/e2etests/tests/frameworks/Vsme.kt, dataland-e2etests/src/test/kotlin/org/dataland/e2etests/utils/ApiAccessor.kt, dataland-e2etests/src/test/kotlin/org/dataland/e2etests/utils/testDataProviders/FrameworkTestDataProvider.kt, dataland-e2etests/src/test/kotlin/org/dataland/e2etests/utils/testDataProviders/GeneralTestDataProvider.kt, dataland-e2etests/src/test/kotlin/org/dataland/e2etests/utils/testDataProviders/QaReportTestDataProvider.kt, dataland-e2etests/src/test/kotlin/org/dataland/e2etests/utils/testDataProviders/TestDataProviderUtils.kt, dataland-e2etests/src/test/kotlin/org/dataland/e2etests/utils/testDataProvivders/FrameworkTestDataProvider.kt, dataland-frontend/src/frameworks/custom/EuTaxoNonFinancialsStaticUploadConfig.ts
=> add missing fields to upload page

dataland-community-manager/src/main/kotlin/db/migration/V14__AddNotifyMeImmediatelyColumn.kt
=> DALA-5755: Flyway script for "notify me immediately"

docker-compose.yml
Hinweis: Der Container "external-storage" ließ sich nicht ohne Weiteres aus dem Stack entfernen.
=> Remove EuroDaT connection from stack

dataland-frontend/src/components/pages/AdminAllRequestsOverview.vue, dataland-frontend/src/components/pages/BulkDataRequest.vue, dataland-frontend/src/components/pages/CompanyDataRequestsOverview.vue, dataland-frontend/src/components/pages/MyDataRequestsOverview.vue, dataland-frontend/src/components/pages/QualityAssurance.vue
=> DALA-5793: Fix broken Tabs
